<?php

namespace LIFO\ClassifBundle\Repository;

/**
 * DateTessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateTessonRepository extends \Doctrine\ORM\EntityRepository
{
}
