<?php

namespace LIFO\ClassifBundle\Repository;

/**
 * DecorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecorRepository extends \Doctrine\ORM\EntityRepository
{
}
