<?php

namespace LIFO\ClassifBundle\Repository;

/**
 * EssaiClassificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EssaiClassificationRepository extends \Doctrine\ORM\EntityRepository
{
}
