<?php

namespace LIFO\ClassifBundle\Repository;

/**
 * MoletteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoletteRepository extends \Doctrine\ORM\EntityRepository
{
}
