<?php

namespace LIFO\ClassifBundle\Repository;

/**
 * NumerisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumerisationRepository extends \Doctrine\ORM\EntityRepository
{
}
