<?php

namespace LIFO\ClassifBundle\Repository;

/**
 * NumIsolationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumIsolationRepository extends \Doctrine\ORM\EntityRepository
{
}
