<?php

namespace LIFO\ClassifBundle\Repository;

/**
 * PeriodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodeRepository extends \Doctrine\ORM\EntityRepository
{
}
