<?php

namespace LIFO\ClassifBundle\Repository;

/**
 * PhaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhaseRepository extends \Doctrine\ORM\EntityRepository
{
}
