<?php

namespace LIFO\ClassifBundle\Repository;

/**
 * PropositionClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropositionClasseRepository extends \Doctrine\ORM\EntityRepository
{
}
