<?php

namespace LIFO\ClassifBundle\Repository;

/**
 * TessonMoletteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TessonMoletteRepository extends \Doctrine\ORM\EntityRepository
{
}
