<?php

namespace LIFO\ClassifBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TessonRepository extends \Doctrine\ORM\EntityRepository {
	
	public function findNumIsolationMax($us_id) {

		$query = $this->_em->createQuery("SELECT MAX(t.numIsolation) FROM LIFOClassifBundle:Tesson t JOIN t.us u WHERE u.id = :us_id");
		$query->setParameter('us_id', $us_id);
		return $query->getSingleScalarResult();
	}
}
