<?php

namespace LIFO\ClassifBundle\Repository;

/**
 * TessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TessonRepository extends \Doctrine\ORM\EntityRepository
{
}
