<?php

namespace LIFO\ClassifBundle\Repository;

/**
 * TypageEnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypageEnRepository extends \Doctrine\ORM\EntityRepository
{
}
