<?php

namespace LIFO\ClassifBundle\Repository;

/**
 * TypeNumerisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeNumerisationRepository extends \Doctrine\ORM\EntityRepository
{
}
