<?php

namespace LIFO\ClassifBundle\Repository;

/**
 * TypeClassificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeClassificationRepository extends \Doctrine\ORM\EntityRepository
{
}
