<?php

namespace LIFO\ClassifBundle\Repository;

/**
 * TypeDecorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDecorRepository extends \Doctrine\ORM\EntityRepository
{
}
