<?php

namespace LIFO\ClassifBundle\Repository;

/**
 * USRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class USRepository extends \Doctrine\ORM\EntityRepository
{
}
