lifo_classif:
    path: /
    defaults:
        _controller: LIFOClassifBundle:Platform:index
    
lifo_classif_upload:
    path:     /upload
    defaults: { _controller: LIFOClassifBundle:Platform:upload }
    
lifo_classif_recherche:
    path:     /recherche
    defaults: { _controller: LIFOClassifBundle:Platform:recherche }
    
lifo_classif_classification:
    path:     /classification/{page}
    defaults:
        _controller: LIFOClassifBundle:Platform:classification
        page: 1
    requirements:
        page: \d+
    
lifo_classif_tesson:
    path:     /tesson/{id}
    defaults: { _controller: LIFOClassifBundle:Platform:tesson }
    requirements:
        id: \d+
        
lifo_classif_admin:
    path:     /admin
    defaults: { _controller: LIFOClassifBundle:Admin:admin}
    
lifo_classif_parametres_positionDecor:
    path:     /parametres/positiondecor
    defaults: { _controller: LIFOClassifBundle:Parametres:positionDecor}
    
lifo_classif_parametres_typeDecor:
    path:     /parametres/typedecor
    defaults: { _controller: LIFOClassifBundle:Parametres:typeDecor}
    
lifo_classif_admin_utilisateur:
    path:     /admin/utilisateur
    defaults: { _controller: LIFOClassifBundle:Admin:utilisateur}
    
lifo_classif_admin_utilisateur_rechercher:
    path:     /admin/utilisateur/rechercher
    defaults: { _controller: LIFOClassifBundle:Admin:utilisateurRechercher}
    
lifo_classif_admin_utilisateur_afficherTous:
    path:     /admin/utilisateur/afficherTous/{page}
    defaults:
        _controller: LIFOClassifBundle:Admin:utilisateurAfficherTous
        page: 1
    requirements:
        page: \d+
    
lifo_classif_admin_utilisateur_afficher:
    path:     /admin/utilisateur/afficher/{id}
    defaults: { _controller: LIFOClassifBundle:Admin:utilisateurAfficher}
    requirements:
        id: \d+
        
lifo_classif_telechargement_numerisation:
    path:     /tesson/telecharger/numerisation/{id}
    defaults: { _controller: LIFOClassifBundle:Platform:telechargementNumerisation}
    requirements:
        id: \d+