lifo_classif:
    path: /
    defaults:
        _controller: LIFOClassifBundle:Platform:index
        
lifo_classif_telechargement:
    path:     /telechargement
    defaults: { _controller: LIFOClassifBundle:Platform:telechargement }
    
lifo_classif_upload:
    path:     /upload
    defaults: { _controller: LIFOClassifBundle:Platform:upload }
    
lifo_classif_recherche:
    path:     /recherche
    defaults: { _controller: LIFOClassifBundle:Platform:recherche }
    
lifo_classif_classification:
    path:     /classification
    defaults: { _controller: LIFOClassifBundle:Platform:classification }
    
lifo_classif_tesson:
    path:     /tesson/{id}
    defaults: { _controller: LIFOClassifBundle:Platform:tesson }
    requirements:
        id: \d+
        
lifo_classif_admin:
    path:     /admin
    defaults: { _controller: LIFOClassifBundle:Admin:admin}
    
lifo_classif_admin_suppression:
    path:     /admin/suppression
    defaults: { _controller: LIFOClassifBundle:Admin:suppression}
    
lifo_classif_admin_ajout:
    path:     /admin/ajout
    defaults: { _controller: LIFOClassifBundle:Admin:ajout}
    
lifo_classif_admin_utilisateur:
    path:     /admin/utilisateur
    defaults: { _controller: LIFOClassifBundle:Admin:utilisateur}
    
lifo_classif_admin_all_user:
    path:     /admin/utilisateur/tous
    defaults: { _controller: LIFOClassifBundle:Admin:allUser}
    
lifo_classif_admin_afficher_utilisateur:
    path:     /admin/utilisateur/afficher/{id}
    defaults: { _controller: LIFOClassifBundle:Admin:afficherUtilisateur}
    requirements:
        id: \d+