<?php

namespace Proxies\__CG__\LIFO\ClassifBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Site extends \LIFO\ClassifBundle\Entity\Site implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'LIFO\\ClassifBundle\\Entity\\Site' . "\0" . 'id', '' . "\0" . 'LIFO\\ClassifBundle\\Entity\\Site' . "\0" . 'codeINSEE', '' . "\0" . 'LIFO\\ClassifBundle\\Entity\\Site' . "\0" . 'numSiteCommune', '' . "\0" . 'LIFO\\ClassifBundle\\Entity\\Site' . "\0" . 'periode', '' . "\0" . 'LIFO\\ClassifBundle\\Entity\\Site' . "\0" . 'zone'];
        }

        return ['__isInitialized__', '' . "\0" . 'LIFO\\ClassifBundle\\Entity\\Site' . "\0" . 'id', '' . "\0" . 'LIFO\\ClassifBundle\\Entity\\Site' . "\0" . 'codeINSEE', '' . "\0" . 'LIFO\\ClassifBundle\\Entity\\Site' . "\0" . 'numSiteCommune', '' . "\0" . 'LIFO\\ClassifBundle\\Entity\\Site' . "\0" . 'periode', '' . "\0" . 'LIFO\\ClassifBundle\\Entity\\Site' . "\0" . 'zone'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Site $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeINSEE($codeINSEE)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeINSEE', [$codeINSEE]);

        return parent::setCodeINSEE($codeINSEE);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeINSEE()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeINSEE', []);

        return parent::getCodeINSEE();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumSiteCommune($numSiteCommune)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumSiteCommune', [$numSiteCommune]);

        return parent::setNumSiteCommune($numSiteCommune);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumSiteCommune()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumSiteCommune', []);

        return parent::getNumSiteCommune();
    }

    /**
     * {@inheritDoc}
     */
    public function addPeriode(\LIFO\ClassifBundle\Entity\Periode $periode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPeriode', [$periode]);

        return parent::addPeriode($periode);
    }

    /**
     * {@inheritDoc}
     */
    public function removePeriode(\LIFO\ClassifBundle\Entity\Periode $periode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePeriode', [$periode]);

        return parent::removePeriode($periode);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriode', []);

        return parent::getPeriode();
    }

    /**
     * {@inheritDoc}
     */
    public function addZone(\LIFO\ClassifBundle\Entity\Zone $zone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addZone', [$zone]);

        return parent::addZone($zone);
    }

    /**
     * {@inheritDoc}
     */
    public function removeZone(\LIFO\ClassifBundle\Entity\Zone $zone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeZone', [$zone]);

        return parent::removeZone($zone);
    }

    /**
     * {@inheritDoc}
     */
    public function getZone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZone', []);

        return parent::getZone();
    }

}
